#!/usr/bin/env python3
# SPDX-License-Identifier: Apache-2.0
#
# gen_uf2_volume.py -- generate the fake FAT16 volume the UF2-style MSC DFU
# sample (samples/usb_msc_dfu_boot) presents to a host.
#
# A UF2 bootloader does not store the file the host writes: it publishes a
# fixed FAT volume so the host can mount it and copy a .uf2 onto it, and it
# parses the *writes* as a UF2 block stream (see the sample's src/main.c).
# The volume is a claim -- 64 MB here -- and the sample synthesizes every
# sector except the two this tool emits:
#
#   sector 0            the FAT16 boot sector (BPB)
#   FAT1/FAT2 sector 0  entries 0/1 (F8 FF FF FF: fixed disk, clean)
#
# Everything else (the rest of both FATs, the root directory, the data
# clusters) reads back as zeroes, which is exactly what an empty FAT16
# volume holds. The sample overlays whatever the host writes to the
# metadata region on top.
#
# The output is a C header (checked in next to the sample, like the
# generated pinctrl dtsi); regenerate with:
#
#   tools/gen_uf2_volume.py --out samples/usb_msc_dfu_boot/src/uf2_volume.h
#
# --size-mib 64 and the geometry below must match what the sample reports
# (the header carries the numbers, so the C code does not repeat them).

import argparse
import struct
import sys

SECTOR = 512


def geometry(size_mib, sectors_per_cluster, root_entries):
    total = size_mib * 1024 * 1024 // SECTOR
    root_sectors = (root_entries * 32 + SECTOR - 1) // SECTOR

    # FAT size: iterate to a fixed point (clusters depend on the FAT size).
    fat_sectors = 1
    for _ in range(64):
        data = total - (1 + 2 * fat_sectors + root_sectors)
        clusters = data // sectors_per_cluster
        need = ((clusters + 2) * 2 + SECTOR - 1) // SECTOR
        if need == fat_sectors:
            break
        fat_sectors = need

    data = total - (1 + 2 * fat_sectors + root_sectors)
    clusters = data // sectors_per_cluster
    if not (4085 <= clusters <= 65524):
        raise SystemExit(
            f"geometry gives {clusters} clusters, outside the FAT16 range "
            f"4085..65524; pick another cluster size / volume size")
    if (clusters + 2) * 2 > fat_sectors * SECTOR:
        raise SystemExit("FAT is too small for the cluster count")

    return dict(total=total, spc=sectors_per_cluster, rsvd=1, nfats=2,
                root_entries=root_entries, root_sectors=root_sectors,
                fat_sectors=fat_sectors, clusters=clusters,
                data_start=1 + 2 * fat_sectors + root_sectors)


def boot_sector(g, label, volume_id):
    b = bytearray(SECTOR)
    b[0:3] = b"\xeb\x3c\x90"                # jmp + nop
    b[3:11] = b"AGMUF2  "                   # OEM name
    struct.pack_into("<H", b, 0x0B, SECTOR)
    b[0x0D] = g["spc"]
    struct.pack_into("<H", b, 0x0E, g["rsvd"])
    b[0x10] = g["nfats"]
    struct.pack_into("<H", b, 0x11, g["root_entries"])
    struct.pack_into("<H", b, 0x13, 0 if g["total"] > 0xFFFF else g["total"])
    b[0x15] = 0xF8                          # media: fixed disk
    struct.pack_into("<H", b, 0x16, g["fat_sectors"])
    struct.pack_into("<H", b, 0x18, 63)     # sectors per track
    struct.pack_into("<H", b, 0x1A, 255)    # heads
    struct.pack_into("<I", b, 0x1C, 0)      # hidden sectors
    struct.pack_into("<I", b, 0x20, g["total"])
    b[0x24] = 0x80                          # drive number
    b[0x25] = 0
    b[0x26] = 0x29                          # extended boot signature
    struct.pack_into("<I", b, 0x27, volume_id)
    b[0x2B:0x36] = label.encode("ascii").ljust(11)[:11]
    b[0x36:0x3E] = b"FAT16   "
    b[0x1FE:0x200] = b"\x55\xaa"
    return bytes(b)


def fat_sector0():
    b = bytearray(SECTOR)
    struct.pack_into("<HH", b, 0, 0xFFF8, 0xFFFF)
    return bytes(b)


def emit(path, g, boot, fat, size_mib, label, volume_id):
    def arr(name, data):
        out = [f"static const uint8_t {name}[{SECTOR}] = {{"]
        for i in range(0, len(data), 12):
            row = ", ".join(f"0x{v:02x}" for v in data[i:i + 12])
            out.append(f"\t{row},")
        out.append("};")
        return "\n".join(out)

    text = f"""\
/*
 * Generated by tools/gen_uf2_volume.py -- do not edit.
 *
 * The fake FAT16 volume {size_mib} MiB ({label}), as the UF2-style MSC DFU
 * sample presents it: sector 0 and the first sector of each FAT copy.
 * Every other sector of the volume reads back as zero (an empty FAT16
 * volume); see src/main.c.
 *
 * Regenerate: tools/gen_uf2_volume.py --out <this file>
 */

#ifndef UF2_VOLUME_H_
#define UF2_VOLUME_H_

#include <stdint.h>

/* Geometry the sample's disk driver has to know. */
#define UF2_VOL_SECTOR_SIZE   {SECTOR}u
#define UF2_VOL_SECTORS       {g['total']}u
#define UF2_VOL_FAT_SECTORS   {g['fat_sectors']}u
#define UF2_VOL_ROOT_SECTORS  {g['root_sectors']}u
#define UF2_VOL_DATA_START    {g['data_start']}u
#define UF2_VOL_CLUSTERS      {g['clusters']}u
#define UF2_VOLUME_ID         0x{volume_id:08x}u

{arr('uf2_boot_sector', boot)}

{arr('uf2_fat0', fat)}

#endif /* UF2_VOLUME_H_ */
"""
    with open(path, "w") as f:
        f.write(text)


def main():
    p = argparse.ArgumentParser(
        description="Generate the fake FAT16 volume header the UF2-style "
                    "MSC DFU sample presents to a host.")
    p.add_argument("--out", required=True, help="C header to write")
    p.add_argument("--size-mib", type=int, default=64,
                   help="claimed volume size in MiB (default 64, the UF2 norm)")
    p.add_argument("--sectors-per-cluster", type=int, default=4,
                   help="2 KiB clusters keep a 64 MiB volume inside FAT16")
    p.add_argument("--root-entries", type=int, default=512)
    p.add_argument("--label", default="AGM-DFU")
    p.add_argument("--volume-id", default="0x41474d55")
    args = p.parse_args()

    g = geometry(args.size_mib, args.sectors_per_cluster, args.root_entries)
    boot = boot_sector(g, args.label, int(args.volume_id, 0))
    fat = fat_sector0()

    emit(args.out, g, boot, fat, args.size_mib, args.label,
         int(args.volume_id, 0))

    print(f"{args.out}: {args.size_mib} MiB FAT16, {g['clusters']} clusters "
          f"of {args.sectors_per_cluster * SECTOR} B, data starts at sector "
          f"{g['data_start']}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
